### ISSUE TITLE
Add vocabulary

### ISSUE THREAD

**Issue by trettigIO** [RWTH-EBC/BUDO#6]
**Is your feature request related to a problem? Please describe.**
Needed more vocabulary to represent entities in a building.

**Describe the solution you'd like**
Add vocaulary in standard part:
* System: Sensor - Multisensor (a sensor with datapoins for light and presence for example) - SEN+MLT
* System: Geothermieanlage - Geothermal Plant - GTP

Add vocaulariy in free part, in order to describe the building more precisely (if needed).
* Liegenschaft - Property - P
* Quartier - Qarter - Q
* Bauteil - Part of Building- PT

**What part/vocabulary does this issue concern? Please describe.**
see above

**Comment by fstinner** [comment]
Thanks Tobias for your feature request.

Sensor -> Multisensor will be included in the next version (~11.03.21)

Geothermal Plant -> could you explain the difference between "geothermal probe", "geothermal field" and "Geothermal Plant"? Is the meaning of "Geothermal Plant" the plant inclusive heat exchanger? Where are the boundaries of the plant?

Liegenschaft - Property - P -> splitted Liegenschaft/Standort/Werk - location - L to 
Liegenschaft - property - PTY (P is Pressure)
Standort - location - L
Fabrik - factory - FACT

Quartier - quarter - Q ->  in the next version (~11.03.21)

Bauteil - Part of Building- PT -> is already available: 
Gebäudeteil - section - SC

If you have other ideas, suggestions or have a different opinion, feel free to share them

**Comment by trettigIO** [comment]
>Liegenschaft - Property - P -> splitted Liegenschaft/Standort/Werk - location - L to
Liegenschaft - property - PTY (P is Pressure)
Standort - location - L
Fabrik - factory - FACT

I couldn't find those vocabularies provided in the csv in the repository.

**Comment by fstinner** [comment]
Add vocabulary in Documentation, Google Spreadsheet and Excel Tool (also in CSV)
