### ISSUE TITLE
Change Floor Numbering schema and add vocabulary

### ISSUE THREAD

**Issue by trettigIO** [RWTH-EBC/BUDO#7]
**Is your feature request related to a problem? Please describe.**
Floor numbering after the english system leads to misinterpretation for german users of the BUDO. Therefore I suggest to change the numbering system to.
 - `Ergeschoss` = 0
 - `1. Obergeschoss` = 1

Add Filter to be able to be a System variable. This is common in AKS systems.
Add a Windschutzwächter to the vocabulary.

**Comment by fstinner** [comment]
Solved with Version from 30.01.2022
