### ISSUE TITLE
Proposed new vocabulary

### ISSUE THREAD

**Issue by trettigIO** [RWTH-EBC/BUDO#8]
**Missing vocabulary**
| new vocabulary (german) | new vocabulary (english) |desctiption of vocablurary (optional) | proposed Vacubalry (optional) | proposed vocabulary type |related vocablulary |
|-----|-----|-----|-----|----| ---|
| Alarm System für behinderten WC | Disabled Toilet Alarm System | see german vocabulrary | EQ.ALA+TOIL |  system | EQ.ALA | 
| Brandschutzklappen Modul | fire damper modul |  Für die Steuerung von Brandschutzklappen werden BSK-Module benötigt | ATCR.DAMP+FIRE | DAMP+FIRE |

Anmerkung: Aktor als fehlende Vokabeln wurde bereits vorgeschlagen.
![grafik](https://user-images.githubusercontent.com/63038396/203582516-275c883d-2d51-4543-9906-101810fbab38.png)

**Comment by trettigIO** [comment]
@fstinner I have set up a table with new vocabulary suggestions as discussed. Is that sufficient for you?

**Comment by fstinner** [comment]
Can you explain what is the difference between "Stellantrieb" and "Aktor"? The actuator ("Stellantrieb") is already included in the system.

**Comment by fstinner** [comment]
Everything is included except of "Aktor" as single name with version of 28.12.2022
